---
apiVersion: v1
kind: Service
metadata:
  name: bitwarden-cli
  namespace: external-secrets
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: bitwarden-cli
  ports:
    - name: http
      port: 8087
      targetPort: http
      protocol: TCP
