---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-postgres-configuration-gateway
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-login
    kind: ClusterSecretStore
  target:
    name: external-postgres-configuration-gateway
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        host: "aap-postgres-rw.aap.svc.cluster.local"
        port: "5432"
        database: "gateway"
        username: "gateway"
        password: "{{ .password }}"
        type: "unmanaged"
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: ocp-lab/postgres-gateway
        property: password
