---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - applications/aap-pg-operator.yaml
  - applications/aap-operator.yaml
  - applications/aap-instance.yaml
  - applications/aap-monitoring.yaml
  - applications/monitoring-operator.yaml
  - applications/monitoring-components.yaml
  - applications/devspaces-operator.yaml
  - applications/devspaces-instance.yaml
  - applications/pipelines.yaml
  - applications/web-terminal.yaml
#  - applications/kubeshark.yaml
#  - applications/github-runners.yaml
